(cl:defpackage test01-srv
  (:use )
  (:export
   "ADDTWOINTS"
   "<ADDTWOINTS-REQUEST>"
   "ADDTWOINTS-REQUEST"
   "<ADDTWOINTS-RESPONSE>"
   "ADDTWOINTS-RESPONSE"
   "SETSOMETHINK"
   "<SETSOMETHINK-REQUEST>"
   "SETSOMETHINK-REQUEST"
   "<SETSOMETHINK-RESPONSE>"
   "SETSOMETHINK-RESPONSE"
  ))

