// Generated by gencpp from file test01/AddTwoInts.msg
// DO NOT EDIT!


#ifndef TEST01_MESSAGE_ADDTWOINTS_H
#define TEST01_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <test01/AddTwoIntsRequest.h>
#include <test01/AddTwoIntsResponse.h>


namespace test01
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace test01


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::test01::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::test01::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::test01::AddTwoInts > {
  static const char* value()
  {
    return "test01/AddTwoInts";
  }

  static const char* value(const ::test01::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::test01::AddTwoIntsRequest> should match 
// service_traits::MD5Sum< ::test01::AddTwoInts > 
template<>
struct MD5Sum< ::test01::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::test01::AddTwoInts >::value();
  }
  static const char* value(const ::test01::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::test01::AddTwoIntsRequest> should match 
// service_traits::DataType< ::test01::AddTwoInts > 
template<>
struct DataType< ::test01::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::test01::AddTwoInts >::value();
  }
  static const char* value(const ::test01::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::test01::AddTwoIntsResponse> should match 
// service_traits::MD5Sum< ::test01::AddTwoInts > 
template<>
struct MD5Sum< ::test01::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::test01::AddTwoInts >::value();
  }
  static const char* value(const ::test01::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::test01::AddTwoIntsResponse> should match 
// service_traits::DataType< ::test01::AddTwoInts > 
template<>
struct DataType< ::test01::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::test01::AddTwoInts >::value();
  }
  static const char* value(const ::test01::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TEST01_MESSAGE_ADDTWOINTS_H
