/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by gensrv_cpp from file /home/krajcovic/workspace/sources/ros/catkin_ws/src/test01/srv/SetSomethink.srv
 *
 */


#ifndef TEST01_MESSAGE_SETSOMETHINK_H
#define TEST01_MESSAGE_SETSOMETHINK_H

#include <ros/service_traits.h>


#include <test01/SetSomethinkRequest.h>
#include <test01/SetSomethinkResponse.h>


namespace test01
{

struct SetSomethink
{

typedef SetSomethinkRequest Request;
typedef SetSomethinkResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetSomethink
} // namespace test01


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::test01::SetSomethink > {
  static const char* value()
  {
    return "713e5cf1444846805670f946f08bfc96";
  }

  static const char* value(const ::test01::SetSomethink&) { return value(); }
};

template<>
struct DataType< ::test01::SetSomethink > {
  static const char* value()
  {
    return "test01/SetSomethink";
  }

  static const char* value(const ::test01::SetSomethink&) { return value(); }
};


// service_traits::MD5Sum< ::test01::SetSomethinkRequest> should match 
// service_traits::MD5Sum< ::test01::SetSomethink > 
template<>
struct MD5Sum< ::test01::SetSomethinkRequest>
{
  static const char* value()
  {
    return MD5Sum< ::test01::SetSomethink >::value();
  }
  static const char* value(const ::test01::SetSomethinkRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::test01::SetSomethinkRequest> should match 
// service_traits::DataType< ::test01::SetSomethink > 
template<>
struct DataType< ::test01::SetSomethinkRequest>
{
  static const char* value()
  {
    return DataType< ::test01::SetSomethink >::value();
  }
  static const char* value(const ::test01::SetSomethinkRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::test01::SetSomethinkResponse> should match 
// service_traits::MD5Sum< ::test01::SetSomethink > 
template<>
struct MD5Sum< ::test01::SetSomethinkResponse>
{
  static const char* value()
  {
    return MD5Sum< ::test01::SetSomethink >::value();
  }
  static const char* value(const ::test01::SetSomethinkResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::test01::SetSomethinkResponse> should match 
// service_traits::DataType< ::test01::SetSomethink > 
template<>
struct DataType< ::test01::SetSomethinkResponse>
{
  static const char* value()
  {
    return DataType< ::test01::SetSomethink >::value();
  }
  static const char* value(const ::test01::SetSomethinkResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TEST01_MESSAGE_SETSOMETHINK_H
