// Generated by gencpp from file test01/SetSomethinkRequest.msg
// DO NOT EDIT!


#ifndef TEST01_MESSAGE_SETSOMETHINKREQUEST_H
#define TEST01_MESSAGE_SETSOMETHINKREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace test01
{
template <class ContainerAllocator>
struct SetSomethinkRequest_
{
  typedef SetSomethinkRequest_<ContainerAllocator> Type;

  SetSomethinkRequest_()
    : A(0)
    , B(0)  {
    }
  SetSomethinkRequest_(const ContainerAllocator& _alloc)
    : A(0)
    , B(0)  {
    }



   typedef int64_t _A_type;
  _A_type A;

   typedef int64_t _B_type;
  _B_type B;




  typedef boost::shared_ptr< ::test01::SetSomethinkRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::test01::SetSomethinkRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetSomethinkRequest_

typedef ::test01::SetSomethinkRequest_<std::allocator<void> > SetSomethinkRequest;

typedef boost::shared_ptr< ::test01::SetSomethinkRequest > SetSomethinkRequestPtr;
typedef boost::shared_ptr< ::test01::SetSomethinkRequest const> SetSomethinkRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::test01::SetSomethinkRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::test01::SetSomethinkRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace test01

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'test01': ['/home/krajcovic/workspace/sources/ros/catkin_ws/src/test01/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::test01::SetSomethinkRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::test01::SetSomethinkRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::test01::SetSomethinkRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::test01::SetSomethinkRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test01::SetSomethinkRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test01::SetSomethinkRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::test01::SetSomethinkRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "02f05bb5bde9ff0aeeed7cca0d2e13fc";
  }

  static const char* value(const ::test01::SetSomethinkRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x02f05bb5bde9ff0aULL;
  static const uint64_t static_value2 = 0xeeed7cca0d2e13fcULL;
};

template<class ContainerAllocator>
struct DataType< ::test01::SetSomethinkRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "test01/SetSomethinkRequest";
  }

  static const char* value(const ::test01::SetSomethinkRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::test01::SetSomethinkRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 A\n\
int64 B\n\
";
  }

  static const char* value(const ::test01::SetSomethinkRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::test01::SetSomethinkRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.A);
      stream.next(m.B);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct SetSomethinkRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::test01::SetSomethinkRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::test01::SetSomethinkRequest_<ContainerAllocator>& v)
  {
    s << indent << "A: ";
    Printer<int64_t>::stream(s, indent + "  ", v.A);
    s << indent << "B: ";
    Printer<int64_t>::stream(s, indent + "  ", v.B);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TEST01_MESSAGE_SETSOMETHINKREQUEST_H
