// Generated by gencpp from file test01/SetSomethink.msg
// DO NOT EDIT!


#ifndef TEST01_MESSAGE_SETSOMETHINK_H
#define TEST01_MESSAGE_SETSOMETHINK_H

#include <ros/service_traits.h>


#include <test01/SetSomethinkRequest.h>
#include <test01/SetSomethinkResponse.h>


namespace test01
{

struct SetSomethink
{

typedef SetSomethinkRequest Request;
typedef SetSomethinkResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetSomethink
} // namespace test01


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::test01::SetSomethink > {
  static const char* value()
  {
    return "713e5cf1444846805670f946f08bfc96";
  }

  static const char* value(const ::test01::SetSomethink&) { return value(); }
};

template<>
struct DataType< ::test01::SetSomethink > {
  static const char* value()
  {
    return "test01/SetSomethink";
  }

  static const char* value(const ::test01::SetSomethink&) { return value(); }
};


// service_traits::MD5Sum< ::test01::SetSomethinkRequest> should match 
// service_traits::MD5Sum< ::test01::SetSomethink > 
template<>
struct MD5Sum< ::test01::SetSomethinkRequest>
{
  static const char* value()
  {
    return MD5Sum< ::test01::SetSomethink >::value();
  }
  static const char* value(const ::test01::SetSomethinkRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::test01::SetSomethinkRequest> should match 
// service_traits::DataType< ::test01::SetSomethink > 
template<>
struct DataType< ::test01::SetSomethinkRequest>
{
  static const char* value()
  {
    return DataType< ::test01::SetSomethink >::value();
  }
  static const char* value(const ::test01::SetSomethinkRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::test01::SetSomethinkResponse> should match 
// service_traits::MD5Sum< ::test01::SetSomethink > 
template<>
struct MD5Sum< ::test01::SetSomethinkResponse>
{
  static const char* value()
  {
    return MD5Sum< ::test01::SetSomethink >::value();
  }
  static const char* value(const ::test01::SetSomethinkResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::test01::SetSomethinkResponse> should match 
// service_traits::DataType< ::test01::SetSomethink > 
template<>
struct DataType< ::test01::SetSomethinkResponse>
{
  static const char* value()
  {
    return DataType< ::test01::SetSomethink >::value();
  }
  static const char* value(const ::test01::SetSomethinkResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TEST01_MESSAGE_SETSOMETHINK_H
